In [3]:
import mne
import numpy as np
import pandas as pd

from ieeg_prep.task_analysis import (
    DEFAULT_EVENT_CODES,
    get_trial_word_boundaries_from_block,
    compute_response_vector,
    permutation_test,
    load_block
)

In [4]:
envelope_fif_path="/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0636/preprocessed/preprocessed_envelope_ieeg.fif"
events_path= "/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0636/preprocessed/preprocessed_events.npy"
blocks_info_path="/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0636/preprocessed/blocks_info.json"
electrodes_csv_path="/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0636/preprocessed/electrodes.csv"

In [5]:
event_codes = DEFAULT_EVENT_CODES
n_words = 12

In [17]:
events = np.load(events_path)
ind_list = np.arange(events.shape[0])
start_ind = ind_list[events[:,2]==1]
end_ind = ind_list[events[:,2]==2]
start_ind[0]

np.int64(0)

In [24]:
for start, end in zip(start_ind, end_ind):
    block_events = events[start:end+1,2] 
    print(np.shape(block_events))
    print(np.sum(block_events == 5))
    print(events[start:end+1] )

(86,)
5
[[ 8627     0     1]
 [ 8755     0     6]
 [12116     0     5]
 [12123     0     8]
 [12140     0     4]
 [12272     0     4]
 [12404     0     4]
 [12536     0     4]
 [12668     0     4]
 [12800     0     4]
 [12932     0     4]
 [13064     0     4]
 [13196     0     4]
 [13328     0     4]
 [13460     0     4]
 [13592     0     4]
 [13724     0     9]
 [13820     0     8]
 [13844     0     5]
 [13850     0     8]
 [13868     0     4]
 [13993     0     7]
 [14000     0     4]
 [14132     0     4]
 [14264     0     4]
 [14396     0     4]
 [14528     0     4]
 [14660     0     4]
 [14792     0     4]
 [14924     0     4]
 [15056     0     4]
 [15188     0     4]
 [15320     0     4]
 [15452     0     9]
 [15548     0     8]
 [15573     0     5]
 [15580     0     8]
 [15596     0     4]
 [15694     0     7]
 [15728     0     4]
 [15860     0     4]
 [15992     0     4]
 [16124     0     4]
 [16256     0     4]
 [16388     0     4]
 [16520     0     4]
 [16652     0     4]
 [16784     0     4]
 [16916     0     4]
 [17048     0     4]
 [17180     0     9]
 [17276     0     8]
 [17286     0     7]
 [17300     0     5]
 [17307     0     8]
 [17324     0     3]
 [17456     0     3]
 [17588     0     3]
 [17720     0     3]
 [17852     0     3]
 [17984     0     3]
 [18116     0     3]
 [18248     0     3]
 [18380     0     3]
 [18512     0     3]
 [18644     0     3]
 [18777     0     3]
 [18908     0     9]
 [19004     0     8]
 [19023     0     7]
 [19030     0     5]
 [19037     0     8]
 [19052     0     3]
 [19184     0     3]
 [19316     0     3]
 [19448     0     3]
 [19580     0     3]
 [19712     0     3]
 [19844     0     3]
 [19976     0     3]
 [20108     0     3]
 [20240     0     3]
 [20372     0     3]
 [20504     0     3]
 [20636     0     9]
 [20831     0     2]]
(126,)
8
[[33755     0     1]
 [33884     0     6]
 [37244     0     5]
 [37251     0     8]
 [37269     0     4]
 [37437     0     4]
 [37605     0     4]
 [37773     0     4]
 [37941     0     4]
 [38108     0     4]
 [38277     0     4]
 [38444     0     4]
 [38613     0     4]
 [38780     0     4]
 [38948     0     4]
 [39117     0     4]
 [39285     0     9]
 [39380     0     8]
 [39404     0     5]
 [39411     0     8]
 [39418     0     7]
 [39428     0     4]
 [39596     0     4]
 [39765     0     4]
 [39933     0     4]
 [40101     0     4]
 [40268     0     4]
 [40437     0     4]
 [40605     0     4]
 [40773     0     4]
 [40941     0     4]
 [41108     0     4]
 [41277     0     4]
 [41444     0     9]
 [41540     0     8]
 [41564     0     7]
 [41570     0     5]
 [41578     0     8]
 [41590     0     4]
 [41757     0     4]
 [41924     0     4]
 [42092     0     4]
 [42260     0     4]
 [42428     0     4]
 [42598     0     4]
 [42765     0     4]
 [42933     0     4]
 [43100     0     4]
 [43269     0     4]
 [43437     0     4]
 [43604     0     9]
 [43700     0     8]
 [43718     0     7]
 [43724     0     5]
 [43731     0     8]
 [43749     0     3]
 [43917     0     3]
 [44085     0     3]
 [44252     0     3]
 [44420     0     3]
 [44588     0     3]
 [44758     0     3]
 [44924     0     3]
 [45092     0     3]
 [45260     0     3]
 [45428     0     3]
 [45596     0     3]
 [45765     0     9]
 [45860     0     8]
 [45884     0     5]
 [45891     0     8]
 [45908     0     3]
 [45994     0     7]
 [46076     0     3]
 [46244     0     3]
 [46412     0     3]
 [46580     0     3]
 [46748     0     3]
 [46917     0     3]
 [47084     0     3]
 [47252     0     3]
 [47421     0     3]
 [47588     0     3]
 [47756     0     3]
 [47925     0     9]
 [48021     0     8]
 [48044     0     5]
 [48051     0     8]
 [48058     0     7]
 [48068     0     3]
 [48236     0     3]
 [48404     0     3]
 [48572     0     3]
 [48740     0     3]
 [48908     0     3]
 [49076     0     3]
 [49244     0     3]
 [49412     0     3]
 [49580     0     3]
 [49748     0     3]
 [49917     0     3]
 [50084     0     9]
 [50180     0     8]
 [50204     0     5]
 [50210     0     8]
 [50228     0     3]
 [50397     0     3]
 [50564     0     3]
 [50732     0     3]
 [50900     0     3]
 [51068     0     3]
 [51236     0     3]
 [51404     0     3]
 [51572     0     3]
 [51740     0     3]
 [51908     0     3]
 [52076     0     3]
 [52245     0     9]
 [52340     0     8]
 [52364     0     5]
 [52371     0     8]
 [52388     0     3]
 [52556     0     3]
 [52724     0     3]
 [52892     0     3]
 [53141     0     2]]
(35,)
2
[[69239     0     1]
 [69367     0     6]
 [72727     0     5]
 [72734     0     8]
 [72752     0     4]
 [72956     0     4]
 [73160     0     4]
 [73364     0     4]
 [73568     0     4]
 [73772     0     4]
 [73976     0     4]
 [74179     0     4]
 [74384     0     4]
 [74588     0     4]
 [74792     0     4]
 [74996     0     4]
 [75200     0     9]
 [75296     0     8]
 [75305     0     7]
 [75319     0     5]
 [75326     0     8]
 [75344     0     4]
 [75548     0     4]
 [75752     0     4]
 [75956     0     4]
 [76160     0     4]
 [76364     0     4]
 [76573     0     4]
 [76772     0     4]
 [76976     0     4]
 [77219     0     4]
 [77384     0     4]
 [77588     0     4]
 [77812     0     9]
 [77864     0     2]]
(328,)
20
[[ 85666      0      1]
 [ 85793      0      6]
 [ 89153      0      5]
 [ 89161      0      8]
 [ 89179      0      4]
 [ 89382      0      4]
 [ 89586      0      4]
 [ 89790      0      4]
 [ 89994      0      4]
 [ 90198      0      4]
 [ 90402      0      4]
 [ 90606      0      4]
 [ 90810      0      4]
 [ 91013      0      4]
 [ 91218      0      4]
 [ 91422      0      4]
 [ 91626      0      9]
 [ 91712      0      7]
 [ 91722      0      8]
 [ 91746      0      5]
 [ 91752      0      8]
 [ 91769      0      4]
 [ 91974      0      4]
 [ 92178      0      4]
 [ 92382      0      4]
 [ 92586      0      4]
 [ 92790      0      4]
 [ 92994      0      4]
 [ 93198      0      4]
 [ 93401      0      4]
 [ 93606      0      4]
 [ 93810      0      4]
 [ 94014      0      4]
 [ 94218      0      9]
 [ 94313      0      8]
 [ 94337      0      5]
 [ 94345      0      8]
 [ 94351      0      7]
 [ 94362      0      4]
 [ 94565      0      4]
 [ 94770      0      4]
 [ 94974      0      4]
 [ 95178      0      4]
 [ 95382      0      4]
 [ 95585      0      4]
 [ 95790      0      4]
 [ 95994      0      4]
 [ 96198      0      4]
 [ 96402      0      4]
 [ 96605      0      4]
 [ 96811      0      9]
 [ 96883      0      7]
 [ 96905      0      8]
 [ 96930      0      5]
 [ 96937      0      8]
 [ 96953      0      3]
 [ 97158      0      3]
 [ 97361      0      3]
 [ 97565      0      3]
 [ 97770      0      3]
 [ 97974      0      3]
 [ 98177      0      3]
 [ 98382      0      3]
 [ 98585      0      3]
 [ 98790      0      3]
 [ 98994      0      3]
 [ 99198      0      3]
 [ 99401      0      9]
 [ 99498      0      8]
 [ 99522      0      5]
 [ 99528      0      8]
 [ 99535      0      7]
 [ 99545      0      3]
 [ 99749      0      3]
 [ 99954      0      3]
 [100158      0      3]
 [100362      0      3]
 [100565      0      3]
 [100770      0      3]
 [100974      0      3]
 [101178      0      3]
 [101382      0      3]
 [101585      0      3]
 [101790      0      3]
 [101994      0      9]
 [102089      0      8]
 [102110      0      7]
 [102117      0      5]
 [102124      0      8]
 [102138      0      3]
 [102341      0      3]
 [102546      0      3]
 [102749      0      3]
 [102954      0      3]
 [103158      0      3]
 [103362      0      3]
 [103567      0      3]
 [103769      0      3]
 [103973      0      3]
 [104177      0      3]
 [104382      0      3]
 [104586      0      9]
 [104681      0      8]
 [104705      0      5]
 [104713      0      8]
 [104729      0      3]
 [104934      0      3]
 [105137      0      3]
 [105342      0      3]
 [105545      0      3]
 [105749      0      3]
 [105954      0      3]
 [106158      0      3]
 [106361      0      3]
 [106565      0      3]
 [106770      0      3]
 [106973      0      3]
 [107177      0      9]
 [107273      0      8]
 [107297      0      5]
 [107304      0      8]
 [107322      0      3]
 [107338      0      7]
 [107525      0      3]
 [107729      0      3]
 [107934      0      3]
 [108137      0      3]
 [108341      0      3]
 [108546      0      3]
 [108750      0      3]
 [108953      0      3]
 [109157      0      3]
 [109361      0      3]
 [109567      0      3]
 [109770      0      9]
 [109865      0      8]
 [109880      0      7]
 [109889      0      5]
 [109896      0      8]
 [109913      0      3]
 [110118      0      3]
 [110322      0      3]
 [110526      0      3]
 [110730      0      3]
 [110933      0      3]
 [111137      0      3]
 [111341      0      3]
 [111546      0      3]
 [111749      0      3]
 [111953      0      3]
 [112158      0      3]
 [112361      0      9]
 [112457      0      8]
 [112481      0      5]
 [112488      0      8]
 [112505      0      4]
 [112512      0      7]
 [112710      0      4]
 [112913      0      4]
 [113118      0      4]
 [113321      0      4]
 [113525      0      4]
 [113729      0      4]
 [113933      0      4]
 [114137      0      4]
 [114341      0      4]
 [114545      0      4]
 [114749      0      4]
 [114953      0      9]
 [115049      0      8]
 [115073      0      5]
 [115080      0      8]
 [115088      0      7]
 [115097      0      4]
 [115301      0      4]
 [115506      0      4]
 [115709      0      4]
 [115913      0      4]
 [116117      0      4]
 [116321      0      4]
 [116525      0      4]
 [116730      0      4]
 [116933      0      4]
 [117138      0      4]
 [117341      0      4]
 [117545      0      9]
 [117641      0      8]
 [117655      0      7]
 [117665      0      5]
 [117671      0      8]
 [117689      0      4]
 [117893      0      4]
 [118097      0      4]
 [118301      0      4]
 [118505      0      4]
 [118709      0      4]
 [118913      0      4]
 [119117      0      4]
 [119321      0      4]
 [119525      0      4]
 [119729      0      4]
 [119933      0      4]
 [120137      0      9]
 [120233      0      8]
 [120250      0      7]
 [120257      0      6]
 [123617      0      5]
 [123624      0      8]
 [123641      0      3]
 [123845      0      3]
 [124049      0      3]
 [124253      0      3]
 [124457      0      3]
 [124661      0      3]
 [124866      0      3]
 [125070      0      3]
 [125273      0      3]
 [125478      0      3]
 [125681      0      3]
 [125885      0      3]
 [126089      0      9]
 [126185      0      8]
 [126209      0      5]
 [126216      0      8]
 [126234      0      3]
 [126401      0      7]
 [126437      0      3]
 [126641      0      3]
 [126845      0      3]
 [127049      0      3]
 [127253      0      3]
 [127458      0      3]
 [127662      0      3]
 [127865      0      3]
 [128069      0      3]
 [128273      0      3]
 [128477      0      3]
 [128681      0      9]
 [128777      0      8]
 [128801      0      5]
 [128807      0      8]
 [128813      0      7]
 [128825      0      3]
 [129030      0      3]
 [129233      0      3]
 [129437      0      3]
 [129641      0      3]
 [129845      0      3]
 [130049      0      3]
 [130253      0      3]
 [130457      0      3]
 [130663      0      3]
 [130865      0      3]
 [131069      0      3]
 [131273      0      9]
 [131369      0      8]
 [131389      0      7]
 [131395      0      5]
 [131402      0      8]
 [131417      0      4]
 [131621      0      4]
 [131825      0      4]
 [132029      0      4]
 [132233      0      4]
 [132437      0      4]
 [132641      0      4]
 [132845      0      4]
 [133049      0      4]
 [133253      0      4]
 [133457      0      4]
 [133661      0      4]
 [133865      0      9]
 [133961      0      8]
 [133985      0      5]
 [133991      0      8]
 [133997      0      7]
 [134009      0      4]
 [134213      0      4]
 [134417      0      4]
 [134621      0      4]
 [134825      0      4]
 [135029      0      4]
 [135233      0      4]
 [135437      0      4]
 [135641      0      4]
 [135845      0      4]
 [136049      0      4]
 [136253      0      4]
 [136457      0      9]
 [136553      0      8]
 [136577      0      5]
 [136583      0      8]
 [136593      0      7]
 [136601      0      4]
 [136805      0      4]
 [137010      0      4]
 [137213      0      4]
 [137417      0      4]
 [137621      0      4]
 [137825      0      4]
 [138029      0      4]
 [138233      0      4]
 [138437      0      4]
 [138641      0      4]
 [138845      0      4]
 [139049      0      9]
 [139145      0      8]
 [139169      0      5]
 [139175      0      8]
 [139193      0      3]
 [139397      0      3]
 [139602      0      3]
 [139805      0      3]
 [140009      0      3]
 [140213      0      3]
 [140417      0      3]
 [140621      0      3]
 [140825      0      3]
 [141029      0      3]
 [141233      0      3]
 [141437      0      3]
 [141641      0      9]
 [141737      0      8]
 [141761      0      5]
 [141767      0      8]
 [141785      0      3]
 [141989      0      3]
 [142170      0      2]]
(823,)
48
[[160810      0      1]
 [160810      0      6]
 [160810      0      5]
 ...
 [160810      0      6]
 [160810      0      7]
 [160810      0      2]]
(822,)
48
[[160810      0      1]
 [160810      0      6]
 [160810      0      5]
 ...
 [160810      0      7]
 [160810      0      6]
 [160810      0      2]]

In [6]:
env_raw = mne.io.read_raw_fif(str(envelope_fif_path), preload=True, verbose=False)
bad_ch_set = set(env_raw.info["bads"])

all_picks = mne.pick_types(env_raw.info, misc=True, exclude=[])
all_ch_names = [env_raw.ch_names[i] for i in all_picks]
seeg_names = [ch.replace("_hg", "") for ch in all_ch_names]
bad_seeg_names = [ch.replace("_hg", "") for ch in all_ch_names if ch in bad_ch_set]

envelope_data = env_raw.get_data(picks=all_picks)  # (n_channels, n_samples)


per_block: dict[str, dict] = {}
respvecs: list[np.ndarray] = []
respvec_ideals: list[np.ndarray] = []

FileNotFoundError: fname does not exist: "/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0636/preprocessed/preprocessed_envelope_ieeg.fif"

In [5]:
langloc_blocks = ["langloc1","langloc2"]

In [6]:
for label in langloc_blocks:
        print(f"Processing block: {label}")
        block = load_block(blocks_info_path, label, events)
        trials, bad_trials = get_trial_word_boundaries_from_block(
            block, event_codes=event_codes, n_words=n_words
        )
        if bad_trials:
            print(f"  Warning: {len(bad_trials)} malformed trial(s) skipped in '{label}'")

Processing block: langloc1
Processing block: langloc2

In [7]:
events

array([[  1030,      0,      1],
       [  1061,      0,      6],
       [  1662,      0,      3],
       ...,
       [323810,      0,      4],
       [324711,      0,      4],
       [325180,      0,      5]], shape=(4693, 3))

In [8]:
sum(events[:,0]>-1)

np.int64(4693)

In [9]:
trials

[{'block_start_event_idx': 1126,
  'trial_number': 0,
  'trial_start_event_idx_local': 2,
  'trial_start_event_idx_global': 1128,
  'word_event_indices_local': [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  'word_event_indices_global': [1130,
   1131,
   1132,
   1133,
   1134,
   1135,
   1136,
   1137,
   1138,
   1139,
   1140,
   1141],
  'word_samples': array([110046, 110079, 110112, 110145, 110178, 110211, 110244, 110277,
         110310, 110343, 110376, 110409]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 16,
  'probe_event_idx_global': 1142,
  'probe_sample': 110442,
  'word_bounds': [(110046, 110079),
   (110079, 110112),
   (110112, 110145),
   (110145, 110178),
   (110178, 110211),
   (110211, 110244),
   (110244, 110277),
   (110277, 110310),
   (110310, 110343),
   (110343, 110376),
   (110376, 110409),
   (110409, 110442)]},
 {'block_start_event_idx': 1126,
  'trial_number': 1,
  'trial_start_event_idx_local': 19,
  'trial_start_event_idx_global': 1145,
  'word_event_indices_local': [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
  'word_event_indices_global': [1147,
   1148,
   1149,
   1150,
   1151,
   1152,
   1153,
   1154,
   1155,
   1156,
   1157,
   1158],
  'word_samples': array([110478, 110511, 110544, 110577, 110610, 110643, 110676, 110709,
         110742, 110775, 110808, 110841]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 33,
  'probe_event_idx_global': 1159,
  'probe_sample': 110874,
  'word_bounds': [(110478, 110511),
   (110511, 110544),
   (110544, 110577),
   (110577, 110610),
   (110610, 110643),
   (110643, 110676),
   (110676, 110709),
   (110709, 110742),
   (110742, 110775),
   (110775, 110808),
   (110808, 110841),
   (110841, 110874)]},
 {'block_start_event_idx': 1126,
  'trial_number': 2,
  'trial_start_event_idx_local': 36,
  'trial_start_event_idx_global': 1162,
  'word_event_indices_local': [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
  'word_event_indices_global': [1164,
   1165,
   1166,
   1167,
   1168,
   1169,
   1170,
   1171,
   1172,
   1173,
   1174,
   1175],
  'word_samples': array([110910, 110943, 110976, 111009, 111042, 111075, 111108, 111141,
         111174, 111207, 111240, 111273]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 50,
  'probe_event_idx_global': 1176,
  'probe_sample': 111306,
  'word_bounds': [(110910, 110943),
   (110943, 110976),
   (110976, 111009),
   (111009, 111042),
   (111042, 111075),
   (111075, 111108),
   (111108, 111141),
   (111141, 111174),
   (111174, 111207),
   (111207, 111240),
   (111240, 111273),
   (111273, 111306)]},
 {'block_start_event_idx': 1126,
  'trial_number': 3,
  'trial_start_event_idx_local': 53,
  'trial_start_event_idx_global': 1179,
  'word_event_indices_local': [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
  'word_event_indices_global': [1181,
   1182,
   1183,
   1184,
   1185,
   1186,
   1187,
   1188,
   1189,
   1190,
   1191,
   1192],
  'word_samples': array([111342, 111375, 111408, 111441, 111474, 111507, 111540, 111573,
         111606, 111639, 111672, 111705]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 67,
  'probe_event_idx_global': 1193,
  'probe_sample': 111738,
  'word_bounds': [(111342, 111375),
   (111375, 111408),
   (111408, 111441),
   (111441, 111474),
   (111474, 111507),
   (111507, 111540),
   (111540, 111573),
   (111573, 111606),
   (111606, 111639),
   (111639, 111672),
   (111672, 111705),
   (111705, 111738)]},
 {'block_start_event_idx': 1126,
  'trial_number': 4,
  'trial_start_event_idx_local': 70,
  'trial_start_event_idx_global': 1196,
  'word_event_indices_local': [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
  'word_event_indices_global': [1198,
   1199,
   1200,
   1201,
   1202,
   1203,
   1204,
   1205,
   1206,
   1207,
   1208,
   1209],
  'word_samples': array([111774, 111807, 111840, 111873, 111906, 111940, 111972, 112005,
         112038, 112071, 112104, 112137]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 84,
  'probe_event_idx_global': 1210,
  'probe_sample': 112170,
  'word_bounds': [(111774, 111807),
   (111807, 111840),
   (111840, 111873),
   (111873, 111906),
   (111906, 111940),
   (111940, 111972),
   (111972, 112005),
   (112005, 112038),
   (112038, 112071),
   (112071, 112104),
   (112104, 112137),
   (112137, 112170)]},
 {'block_start_event_idx': 1126,
  'trial_number': 5,
  'trial_start_event_idx_local': 87,
  'trial_start_event_idx_global': 1213,
  'word_event_indices_local': [89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'word_event_indices_global': [1215,
   1216,
   1217,
   1218,
   1219,
   1220,
   1221,
   1222,
   1223,
   1224,
   1225,
   1226],
  'word_samples': array([112206, 112239, 112272, 112305, 112338, 112371, 112404, 112437,
         112470, 112503, 112536, 112569]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 101,
  'probe_event_idx_global': 1227,
  'probe_sample': 112602,
  'word_bounds': [(112206, 112239),
   (112239, 112272),
   (112272, 112305),
   (112305, 112338),
   (112338, 112371),
   (112371, 112404),
   (112404, 112437),
   (112437, 112470),
   (112470, 112503),
   (112503, 112536),
   (112536, 112569),
   (112569, 112602)]},
 {'block_start_event_idx': 1126,
  'trial_number': 6,
  'trial_start_event_idx_local': 104,
  'trial_start_event_idx_global': 1230,
  'word_event_indices_local': [106,
   107,
   108,
   109,
   110,
   111,
   112,
   113,
   114,
   115,
   116,
   117],
  'word_event_indices_global': [1232,
   1233,
   1234,
   1235,
   1236,
   1237,
   1238,
   1239,
   1240,
   1241,
   1242,
   1243],
  'word_samples': array([112638, 112671, 112704, 112737, 112770, 112803, 112836, 112869,
         112902, 112935, 112968, 113001]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 118,
  'probe_event_idx_global': 1244,
  'probe_sample': 113034,
  'word_bounds': [(112638, 112671),
   (112671, 112704),
   (112704, 112737),
   (112737, 112770),
   (112770, 112803),
   (112803, 112836),
   (112836, 112869),
   (112869, 112902),
   (112902, 112935),
   (112935, 112968),
   (112968, 113001),
   (113001, 113034)]},
 {'block_start_event_idx': 1126,
  'trial_number': 7,
  'trial_start_event_idx_local': 121,
  'trial_start_event_idx_global': 1247,
  'word_event_indices_local': [123,
   124,
   125,
   126,
   127,
   128,
   129,
   130,
   131,
   132,
   133,
   134],
  'word_event_indices_global': [1249,
   1250,
   1251,
   1252,
   1253,
   1254,
   1255,
   1256,
   1257,
   1258,
   1259,
   1260],
  'word_samples': array([113070, 113103, 113136, 113169, 113202, 113235, 113268, 113301,
         113334, 113367, 113400, 113433]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 135,
  'probe_event_idx_global': 1261,
  'probe_sample': 113466,
  'word_bounds': [(113070, 113103),
   (113103, 113136),
   (113136, 113169),
   (113169, 113202),
   (113202, 113235),
   (113235, 113268),
   (113268, 113301),
   (113301, 113334),
   (113334, 113367),
   (113367, 113400),
   (113400, 113433),
   (113433, 113466)]},
 {'block_start_event_idx': 1126,
  'trial_number': 8,
  'trial_start_event_idx_local': 138,
  'trial_start_event_idx_global': 1264,
  'word_event_indices_local': [140,
   141,
   142,
   143,
   144,
   145,
   146,
   147,
   148,
   149,
   150,
   151],
  'word_event_indices_global': [1266,
   1267,
   1268,
   1269,
   1270,
   1271,
   1272,
   1273,
   1274,
   1275,
   1276,
   1277],
  'word_samples': array([113502, 113535, 113568, 113601, 113634, 113667, 113700, 113733,
         113766, 113799, 113832, 113865]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 152,
  'probe_event_idx_global': 1278,
  'probe_sample': 113898,
  'word_bounds': [(113502, 113535),
   (113535, 113568),
   (113568, 113601),
   (113601, 113634),
   (113634, 113667),
   (113667, 113700),
   (113700, 113733),
   (113733, 113766),
   (113766, 113799),
   (113799, 113832),
   (113832, 113865),
   (113865, 113898)]},
 {'block_start_event_idx': 1126,
  'trial_number': 9,
  'trial_start_event_idx_local': 154,
  'trial_start_event_idx_global': 1280,
  'word_event_indices_local': [156,
   157,
   158,
   159,
   160,
   161,
   162,
   163,
   164,
   165,
   166,
   167],
  'word_event_indices_global': [1282,
   1283,
   1284,
   1285,
   1286,
   1287,
   1288,
   1289,
   1290,
   1291,
   1292,
   1293],
  'word_samples': array([113934, 113967, 114000, 114033, 114066, 114099, 114132, 114165,
         114198, 114231, 114264, 114297]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 168,
  'probe_event_idx_global': 1294,
  'probe_sample': 114330,
  'word_bounds': [(113934, 113967),
   (113967, 114000),
   (114000, 114033),
   (114033, 114066),
   (114066, 114099),
   (114099, 114132),
   (114132, 114165),
   (114165, 114198),
   (114198, 114231),
   (114231, 114264),
   (114264, 114297),
   (114297, 114330)]},
 {'block_start_event_idx': 1126,
  'trial_number': 10,
  'trial_start_event_idx_local': 171,
  'trial_start_event_idx_global': 1297,
  'word_event_indices_local': [173,
   174,
   175,
   176,
   177,
   178,
   179,
   180,
   181,
   182,
   183,
   184],
  'word_event_indices_global': [1299,
   1300,
   1301,
   1302,
   1303,
   1304,
   1305,
   1306,
   1307,
   1308,
   1309,
   1310],
  'word_samples': array([114366, 114399, 114432, 114465, 114498, 114531, 114564, 114597,
         114630, 114663, 114696, 114729]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 185,
  'probe_event_idx_global': 1311,
  'probe_sample': 114762,
  'word_bounds': [(114366, 114399),
   (114399, 114432),
   (114432, 114465),
   (114465, 114498),
   (114498, 114531),
   (114531, 114564),
   (114564, 114597),
   (114597, 114630),
   (114630, 114663),
   (114663, 114696),
   (114696, 114729),
   (114729, 114762)]},
 {'block_start_event_idx': 1126,
  'trial_number': 11,
  'trial_start_event_idx_local': 188,
  'trial_start_event_idx_global': 1314,
  'word_event_indices_local': [190,
   191,
   192,
   193,
   194,
   195,
   196,
   197,
   198,
   199,
   200,
   201],
  'word_event_indices_global': [1316,
   1317,
   1318,
   1319,
   1320,
   1321,
   1322,
   1323,
   1324,
   1325,
   1326,
   1327],
  'word_samples': array([114798, 114831, 114864, 114897, 114930, 114963, 114996, 115029,
         115063, 115095, 115128, 115161]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 202,
  'probe_event_idx_global': 1328,
  'probe_sample': 115194,
  'word_bounds': [(114798, 114831),
   (114831, 114864),
   (114864, 114897),
   (114897, 114930),
   (114930, 114963),
   (114963, 114996),
   (114996, 115029),
   (115029, 115063),
   (115063, 115095),
   (115095, 115128),
   (115128, 115161),
   (115161, 115194)]},
 {'block_start_event_idx': 1126,
  'trial_number': 12,
  'trial_start_event_idx_local': 206,
  'trial_start_event_idx_global': 1332,
  'word_event_indices_local': [208,
   209,
   210,
   211,
   212,
   213,
   214,
   215,
   216,
   217,
   218,
   219],
  'word_event_indices_global': [1334,
   1335,
   1336,
   1337,
   1338,
   1339,
   1340,
   1341,
   1342,
   1343,
   1344,
   1345],
  'word_samples': array([116070, 116103, 116136, 116169, 116202, 116235, 116268, 116301,
         116334, 116367, 116400, 116433]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 220,
  'probe_event_idx_global': 1346,
  'probe_sample': 116466,
  'word_bounds': [(116070, 116103),
   (116103, 116136),
   (116136, 116169),
   (116169, 116202),
   (116202, 116235),
   (116235, 116268),
   (116268, 116301),
   (116301, 116334),
   (116334, 116367),
   (116367, 116400),
   (116400, 116433),
   (116433, 116466)]},
 {'block_start_event_idx': 1126,
  'trial_number': 13,
  'trial_start_event_idx_local': 223,
  'trial_start_event_idx_global': 1349,
  'word_event_indices_local': [225,
   226,
   227,
   228,
   229,
   230,
   231,
   232,
   233,
   234,
   235,
   236],
  'word_event_indices_global': [1351,
   1352,
   1353,
   1354,
   1355,
   1356,
   1357,
   1358,
   1359,
   1360,
   1361,
   1362],
  'word_samples': array([116502, 116535, 116568, 116601, 116634, 116667, 116700, 116733,
         116766, 116799, 116832, 116865]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 237,
  'probe_event_idx_global': 1363,
  'probe_sample': 116898,
  'word_bounds': [(116502, 116535),
   (116535, 116568),
   (116568, 116601),
   (116601, 116634),
   (116634, 116667),
   (116667, 116700),
   (116700, 116733),
   (116733, 116766),
   (116766, 116799),
   (116799, 116832),
   (116832, 116865),
   (116865, 116898)]},
 {'block_start_event_idx': 1126,
  'trial_number': 14,
  'trial_start_event_idx_local': 240,
  'trial_start_event_idx_global': 1366,
  'word_event_indices_local': [242,
   243,
   244,
   245,
   246,
   247,
   248,
   249,
   250,
   251,
   252,
   253],
  'word_event_indices_global': [1368,
   1369,
   1370,
   1371,
   1372,
   1373,
   1374,
   1375,
   1376,
   1377,
   1378,
   1379],
  'word_samples': array([116934, 116967, 117000, 117033, 117066, 117099, 117132, 117165,
         117198, 117231, 117264, 117297]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 254,
  'probe_event_idx_global': 1380,
  'probe_sample': 117330,
  'word_bounds': [(116934, 116967),
   (116967, 117000),
   (117000, 117033),
   (117033, 117066),
   (117066, 117099),
   (117099, 117132),
   (117132, 117165),
   (117165, 117198),
   (117198, 117231),
   (117231, 117264),
   (117264, 117297),
   (117297, 117330)]},
 {'block_start_event_idx': 1126,
  'trial_number': 15,
  'trial_start_event_idx_local': 257,
  'trial_start_event_idx_global': 1383,
  'word_event_indices_local': [259,
   260,
   261,
   262,
   263,
   264,
   265,
   266,
   267,
   268,
   269,
   270],
  'word_event_indices_global': [1385,
   1386,
   1387,
   1388,
   1389,
   1390,
   1391,
   1392,
   1393,
   1394,
   1395,
   1396],
  'word_samples': array([117366, 117399, 117432, 117465, 117498, 117531, 117564, 117597,
         117630, 117663, 117696, 117729]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 271,
  'probe_event_idx_global': 1397,
  'probe_sample': 117762,
  'word_bounds': [(117366, 117399),
   (117399, 117432),
   (117432, 117465),
   (117465, 117498),
   (117498, 117531),
   (117531, 117564),
   (117564, 117597),
   (117597, 117630),
   (117630, 117663),
   (117663, 117696),
   (117696, 117729),
   (117729, 117762)]},
 {'block_start_event_idx': 1126,
  'trial_number': 16,
  'trial_start_event_idx_local': 274,
  'trial_start_event_idx_global': 1400,
  'word_event_indices_local': [276,
   277,
   278,
   279,
   280,
   281,
   282,
   283,
   284,
   285,
   286,
   287],
  'word_event_indices_global': [1402,
   1403,
   1404,
   1405,
   1406,
   1407,
   1408,
   1409,
   1410,
   1411,
   1412,
   1413],
  'word_samples': array([117798, 117831, 117864, 117897, 117930, 117963, 117996, 118029,
         118062, 118095, 118128, 118161]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 288,
  'probe_event_idx_global': 1414,
  'probe_sample': 118194,
  'word_bounds': [(117798, 117831),
   (117831, 117864),
   (117864, 117897),
   (117897, 117930),
   (117930, 117963),
   (117963, 117996),
   (117996, 118029),
   (118029, 118062),
   (118062, 118095),
   (118095, 118128),
   (118128, 118161),
   (118161, 118194)]},
 {'block_start_event_idx': 1126,
  'trial_number': 17,
  'trial_start_event_idx_local': 291,
  'trial_start_event_idx_global': 1417,
  'word_event_indices_local': [293,
   294,
   295,
   296,
   297,
   298,
   299,
   300,
   301,
   302,
   303,
   304],
  'word_event_indices_global': [1419,
   1420,
   1421,
   1422,
   1423,
   1424,
   1425,
   1426,
   1427,
   1428,
   1429,
   1430],
  'word_samples': array([118230, 118263, 118296, 118329, 118362, 118395, 118428, 118461,
         118494, 118527, 118560, 118593]),
  'word_codes': array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
  'probe_event_idx_local': 305,
  'probe_event_idx_global': 1431,
  'probe_sample': 118626,
  'word_bounds': [(118230, 118263),
   (118263, 118296),
   (118296, 118329),
   (118329, 118362),
   (118362, 118395),
   (118395, 118428),
   (118428, 118461),
   (118461, 118494),
   (118494, 118527),
   (118527, 118560),
   (118560, 118593),
   (118593, 118626)]},
 {'block_start_event_idx': 1126,
  'trial_number': 18,
  'trial_start_event_idx_local': 308,
  'trial_start_event_idx_global': 1434,
  'word_event_indices_local': [310,
   311,
   312,
   313,
   314,
   315,
   316,
   317,
   318,
   319,
   320,
   321],
  'word_event_indices_global': [1436,
   1437,
   1438,
   1439,
   1440,
   1441,
   1442,
   1443,
   1444,
   1445,
   1446,
   1447],
  'word_samples': array([118662, 118695, 118728, 118761, 118794, 118827, 118860, 118893,
         118926, 118959, 118992, 119025]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 322,
  'probe_event_idx_global': 1448,
  'probe_sample': 119058,
  'word_bounds': [(118662, 118695),
   (118695, 118728),
   (118728, 118761),
   (118761, 118794),
   (118794, 118827),
   (118827, 118860),
   (118860, 118893),
   (118893, 118926),
   (118926, 118959),
   (118959, 118992),
   (118992, 119025),
   (119025, 119058)]},
 {'block_start_event_idx': 1126,
  'trial_number': 19,
  'trial_start_event_idx_local': 325,
  'trial_start_event_idx_global': 1451,
  'word_event_indices_local': [327,
   328,
   329,
   330,
   331,
   332,
   333,
   334,
   335,
   336,
   337,
   338],
  'word_event_indices_global': [1453,
   1454,
   1455,
   1456,
   1457,
   1458,
   1459,
   1460,
   1461,
   1462,
   1463,
   1464],
  'word_samples': array([119094, 119127, 119160, 119193, 119226, 119259, 119292, 119325,
         119358, 119391, 119424, 119456]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 339,
  'probe_event_idx_global': 1465,
  'probe_sample': 119490,
  'word_bounds': [(119094, 119127),
   (119127, 119160),
   (119160, 119193),
   (119193, 119226),
   (119226, 119259),
   (119259, 119292),
   (119292, 119325),
   (119325, 119358),
   (119358, 119391),
   (119391, 119424),
   (119424, 119456),
   (119456, 119490)]},
 {'block_start_event_idx': 1126,
  'trial_number': 20,
  'trial_start_event_idx_local': 341,
  'trial_start_event_idx_global': 1467,
  'word_event_indices_local': [344,
   345,
   346,
   347,
   348,
   349,
   350,
   351,
   352,
   353,
   354,
   355],
  'word_event_indices_global': [1470,
   1471,
   1472,
   1473,
   1474,
   1475,
   1476,
   1477,
   1478,
   1479,
   1480,
   1481],
  'word_samples': array([119526, 119559, 119592, 119625, 119658, 119691, 119724, 119757,
         119790, 119823, 119856, 119889]),
  'word_codes': array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
  'probe_event_idx_local': 356,
  'probe_event_idx_global': 1482,
  'probe_sample': 119922,
  'word_bounds': [(119526, 119559),
   (119559, 119592),
   (119592, 119625),
   (119625, 119658),
   (119658, 119691),
   (119691, 119724),
   (119724, 119757),
   (119757, 119790),
   (119790, 119823),
   (119823, 119856),
   (119856, 119889),
   (119889, 119922)]},
 {'block_start_event_idx': 1126,
  'trial_number': 21,
  'trial_start_event_idx_local': 358,
  'trial_start_event_idx_global': 1484,
  'word_event_indices_local': [360,
   361,
   362,
   363,
   364,
   365,
   366,
   367,
   368,
   369,
   370,
   371],
  'word_event_indices_global': [1486,
   1487,
   1488,

In [10]:
langloc_blocks = []
for idx, block in enumerate(complete_blocks):
    num_trials = np.sum(np.asarray(block["events"]) == 6)
    print(f"Block {idx}: {num_trials} trials")
    num_nw_conds = np.sum(np.asarray(block["events"]) == 4)
    print(f"Block {idx}: {num_nw_conds} non word conditions")
    if num_trials == 48:
        langloc_blocks.append(block)

NameError: name 'complete_blocks' is not defined

In [44]:
ied = np.load("/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0004/processed/ied_results.npz", allow_pickle=True)

In [45]:
 coordinates_csv= "/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0004/tasks_raw/sub-EMOP0004_ses-ieeg1_atlas-CerebrAThomasMiddle_electrodes.csv"

In [46]:
ied["channel_spike_rates"]

array([1.88452422e+00, 1.34451435e+00, 6.06133520e-01, 8.70628147e-01,
       3.96741940e-01, 2.97556455e-01, 2.75515236e-01, 2.64494627e-01,
       1.24532887e+00, 5.28989254e-01, 1.33349374e+00, 6.17154130e-01,
       4.40824378e-01, 7.05319005e-01, 4.18783159e-01, 5.95112911e-01,
       3.30618284e-01, 3.08577065e-01, 2.75515236e-01, 3.19597674e-01,
       3.19597674e-01, 1.54288532e-01, 1.32247313e-01, 2.09391580e-01,
       3.08577065e-01, 2.31432799e-01, 4.40824378e-01, 3.19597674e-01,
       8.37566319e-01, 3.74700722e-01, 3.19597674e-01, 2.64494627e-01,
       2.20412189e-01, 1.85146239e+00, 8.48586928e-01, 1.10206095e-01,
       1.43267923e-01, 2.31432799e-01, 1.19022582e+00, 1.96166848e+00,
       6.17154130e-01, 5.73071692e-01, 5.17968645e-01, 2.09391580e-01,
       9.03689976e-01, 7.16339615e-01, 3.41638893e-01, 2.53474018e-01,
       2.42453408e-01, 2.75515236e-01, 3.08577065e-01, 8.37566319e-01,
       1.10206095e-01, 1.87350361e-01, 1.10206095e-01, 6.50215958e-01,
       2.36943103e+00, 3.93435758e+00, 5.62051082e+00, 5.24581010e+00,
       6.06133520e-01, 9.36751804e-01, 7.60422053e-01, 4.73886207e-01,
       3.63680112e-01, 1.23430826e+00, 2.67800810e+00, 2.89842029e+00,
       7.71442662e-01, 6.61236567e-01, 6.94298396e-01, 3.63680112e-01,
       6.61236567e-02, 4.40824378e-02, 4.40824378e-02, 3.30618284e-02,
       3.30618284e-02, 4.40824378e-02, 4.40824378e-02, 7.71442662e-02,
       2.31432799e-01, 6.28174739e-01, 7.05319005e-01, 1.87350361e-01,
       6.61236567e-02, 8.81648757e-02, 5.95112911e-01, 5.40009863e-01,
       1.32247313e-01, 1.21226704e-01, 1.65309142e-01, 2.09391580e-01,
       2.42453408e-01, 2.20412189e-02, 6.61236567e-02, 1.32247313e-01,
       9.91854851e-02, 2.53474018e-01, 1.21226704e+00, 2.67800810e+00,
       3.40536832e+00, 3.94537819e+00, 3.97844001e+00, 4.40824378e-02,
       4.40824378e-02, 3.30618284e-02, 5.51030473e-02, 6.61236567e-02,
       3.30618284e-02, 4.40824378e-02, 3.30618284e-02, 3.30618284e-02,
       2.20412189e-02, 2.20412189e-02, 1.21226704e-01, 7.71442662e-02,
       3.30618284e-02, 4.40824378e-02, 5.51030473e-02, 6.61236567e-02,
       5.51030473e-02, 5.51030473e-02, 6.61236567e-02, 2.20412189e-02,
       7.71442662e-02, 1.21226704e-01, 1.43267923e-01, 1.49329258e+01,
       1.15055163e+01, 1.02822286e+01, 1.26957421e+01, 1.13071453e+01,
       1.08663209e+01, 9.67609510e+00, 8.14423039e+00, 6.48011836e+00,
       4.20987281e+00, 2.58984322e+00, 1.86248300e+00, 1.42165862e+00,
       1.86248300e+00, 1.41614832e+01, 1.47786373e+01, 1.57925334e+01,
       1.15826605e+01, 9.00383793e+00, 7.71442662e+00, 6.33685044e+00,
       4.57355293e+00, 3.20699735e+00, 2.44657530e+00, 1.95064787e+00,
       1.73023568e+00, 1.21226704e+00, 1.10206095e+01, 1.02932492e+01,
       7.85769454e+00, 4.06660489e+00, 4.36416135e+00, 2.99760577e+00,
       1.84044178e+00, 1.28941131e+00, 1.35553496e+00, 4.08864611e+00,
       1.53186471e+00, 1.10206095e+00, 2.27575585e+01, 1.56713066e+01,
       1.54398739e+01, 1.29051337e+01, 8.98179671e+00, 4.22089342e+00,
       2.56780200e+00, 1.31145253e+00, 6.83277786e-01, 1.20124643e+00,
       7.40584956e+00, 5.13560401e+00, 4.92621243e+00, 4.38620256e+00,
       1.89554483e+00, 2.14901884e+00, 1.84044178e+00, 2.72209054e+00,
       6.86583969e+00, 7.75850906e+00, 8.16627161e+00, 7.70340601e+00,
       8.03402429e+00, 6.27072678e+00, 5.37805742e+00, 5.51030473e+00,
       3.01964699e+00, 1.71921508e+00, 1.55390593e+00, 1.10206095e+00,
       3.09679126e+00, 9.14710585e-01, 4.07762550e-01, 1.03593729e+00,
       2.64494627e+00, 2.74413176e+00, 1.92860666e+00, 2.86535846e+00,
       1.55390593e+00, 6.61236567e-01, 1.21226704e+00, 2.60086383e+00,
       5.51030473e-01, 3.08577065e-01, 1.38859679e+00, 3.58169807e+00,
       8.48586928e-01, 2.81025541e+00, 3.96741940e+00, 4.24293464e+00,
       4.44130561e+00, 4.11068733e+00, 2.97556455e+00, 1.05797851e+00,
       1.54288532e-01, 3.08577065e-01, 1.87350361e-01, 7.71442662e-02,
       9.91854851e-02, 4.29803769e-01, 3.85721331e-01, 9.25731194e-01,
       2.56780200e+00, 1.54288532e-01, 2.97556455e-01, 9.91854851e-01,
       4.07762550e-01, 2.31432799e-01, 8.81648757e-02, 4.18783159e-01,
       1.98370970e-01, 9.91854851e-02, 9.91854851e-02, 1.21226704e-01,
       1.54288532e-01, 2.75515236e-01, 6.06133520e-01, 3.51557442e+00,
       1.82942117e+00, 1.11308156e+00, 1.10206095e-01, 6.61236567e-02,
       4.40824378e-02, 5.51030473e-02, 1.32247313e-01, 2.42453408e-01,
       1.65309142e-01, 9.91854851e-02, 8.81648757e-02])

In [47]:
ied_ch_names = [str(ch) for ch in ied["ch_names"]]

In [48]:
spike_counts = dict(zip(ied_ch_names, ied["channel_spike_counts"]))
spike_rates = dict(zip(ied_ch_names, ied["channel_spike_rates"]))

In [49]:
spike_counts

{'LAm1': np.int64(171),
 'LAm2': np.int64(122),
 'LAm3': np.int64(55),
 'LAm4': np.int64(79),
 'LAm5': np.int64(36),
 'LAm6': np.int64(27),
 'LAm7': np.int64(25),
 'LAm8': np.int64(24),
 'LAm9': np.int64(113),
 'LAm10': np.int64(48),
 'LAm11': np.int64(121),
 'LAm12': np.int64(56),
 'LAm13': np.int64(40),
 'LAHc1': np.int64(64),
 'LAHc2': np.int64(38),
 'LAHc3': np.int64(54),
 'LAHc4': np.int64(30),
 'LAHc5': np.int64(28),
 'LAHc6': np.int64(25),
 'LAHc7': np.int64(29),
 'LAHc8': np.int64(29),
 'LAHc9': np.int64(14),
 'LAHc10': np.int64(12),
 'LAHc11': np.int64(19),
 'LAHc12': np.int64(28),
 'LAHc13': np.int64(21),
 'LMiHc1': np.int64(40),
 'LMiHc2': np.int64(29),
 'LMiHc3': np.int64(76),
 'LMiHc4': np.int64(34),
 'LMiHc5': np.int64(29),
 'LMiHc6': np.int64(24),
 'LMiHc7': np.int64(20),
 'LMiHc8': np.int64(168),
 'LMiHc9': np.int64(77),
 'LMiHc10': np.int64(10),
 'LMiHc11': np.int64(13),
 'LMiHc12': np.int64(21),
 'LTePo1': np.int64(108),
 'LTePo2': np.int64(178),
 'LTePo3': np.int64(56),
 'LTePo4': np.int64(52),
 'LTePo5': np.int64(47),
 'LTePo6': np.int64(19),
 'LTePo7': np.int64(82),
 'LTePo8': np.int64(65),
 'LTePo9': np.int64(31),
 'LTePo10': np.int64(23),
 'LTePo11': np.int64(22),
 'LTePo12': np.int64(25),
 'LTePo13': np.int64(28),
 'LTePo14': np.int64(76),
 'LEc1': np.int64(10),
 'LEc2': np.int64(17),
 'LEc3': np.int64(10),
 'LEc4': np.int64(59),
 'LEc5': np.int64(215),
 'LEc6': np.int64(357),
 'LEc7': np.int64(510),
 'LEc8': np.int64(476),
 'LPHG1': np.int64(55),
 'LPHG2': np.int64(85),
 'LPHG3': np.int64(69),
 'LPHG4': np.int64(43),
 'LPHG5': np.int64(33),
 'LPHG6': np.int64(112),
 'LPHG7': np.int64(243),
 'LPHG8': np.int64(263),
 'LPHG9': np.int64(70),
 'LPHG10': np.int64(60),
 'LPHG11': np.int64(63),
 'LPHG12': np.int64(33),
 'LMiIn1': np.int64(6),
 'LMiIn2': np.int64(4),
 'LMiIn3': np.int64(4),
 'LMiIn4': np.int64(3),
 'LMiIn5': np.int64(3),
 'LMiIn6': np.int64(4),
 'LMiIn7': np.int64(4),
 'LMiIn8': np.int64(7),
 'LMiIn9': np.int64(21),
 'LMiIn10': np.int64(57),
 'LMiIn11': np.int64(64),
 'LMiIn12': np.int64(17),
 'LMiIn13': np.int64(6),
 'LMiIn14': np.int64(8),
 'LMiIn15': np.int64(54),
 'LMiIn16': np.int64(49),
 'LPul1': np.int64(12),
 'LPul2': np.int64(11),
 'LPul3': np.int64(15),
 'LPul4': np.int64(19),
 'LPul5': np.int64(22),
 'LPul6': np.int64(2),
 'LPul7': np.int64(6),
 'LPul8': np.int64(12),
 'LPul9': np.int64(9),
 'LPul10': np.int64(23),
 'LPul11': np.int64(110),
 'LPul12': np.int64(243),
 'LPul13': np.int64(309),
 'LPul14': np.int64(358),
 'LPul15': np.int64(361),
 'LOFc1': np.int64(4),
 'LOFc2': np.int64(4),
 'LOFc3': np.int64(3),
 'LOFc4': np.int64(5),
 'LOFc5': np.int64(6),
 'LOFc6': np.int64(3),
 'LOFc7': np.int64(4),
 'LOFc8': np.int64(3),
 'LOFc9': np.int64(3),
 'LOFc10': np.int64(2),
 'LOFc11': np.int64(2),
 'LOFc12': np.int64(11),
 'LOFc13': np.int64(7),
 'LAIn1': np.int64(3),
 'LAIn2': np.int64(4),
 'LAIn3': np.int64(5),
 'LAIn4': np.int64(6),
 'LAIn5': np.int64(5),
 'LAIn6': np.int64(5),
 'LAIn7': np.int64(6),
 'LAIn8': np.int64(2),
 'LAIn9': np.int64(7),
 'LAIn10': np.int64(11),
 'LAIn11': np.int64(13),
 'RAm1': np.int64(1355),
 'RAm2': np.int64(1044),
 'RAm3': np.int64(933),
 'RAm4': np.int64(1152),
 'RAm5': np.int64(1026),
 'RAm6': np.int64(986),
 'RAm7': np.int64(878),
 'RAm8': np.int64(739),
 'RAm9': np.int64(588),
 'RAm10': np.int64(382),
 'RAm11': np.int64(235),
 'RAm12': np.int64(169),
 'RAm13': np.int64(129),
 'RAm14': np.int64(169),
 'RAHc1': np.int64(1285),
 'RAHc2': np.int64(1341),
 'RAHc3': np.int64(1433),
 'RAHc4': np.int64(1051),
 'RAHc5': np.int64(817),
 'RAHc6': np.int64(700),
 'RAHc7': np.int64(575),
 'RAHc8': np.int64(415),
 'RAHc9': np.int64(291),
 'RAHc10': np.int64(222),
 'RAHc11': np.int64(177),
 'RAHc12': np.int64(157),
 'RAHc13': np.int64(110),
 'RMiHc1': np.int64(1000),
 'RMiHc2': np.int64(934),
 'RMiHc3': np.int64(713),
 'RMiHc4': np.int64(369),
 'RMiHc5': np.int64(396),
 'RMiHc6': np.int64(272),
 'RMiHc7': np.int64(167),
 'RMiHc8': np.int64(117),
 'RMiHc9': np.int64(123),
 'RMiHc10': np.int64(371),
 'RMiHc11': np.int64(139),
 'RMiHc12': np.int64(100),
 'RTePo1': np.int64(2065),
 'RTePo2': np.int64(1422),
 'RTePo3': np.int64(1401),
 'RTePo4': np.int64(1171),
 'RTePo5': np.int64(815),
 'RTePo6': np.int64(383),
 'RTePo7': np.int64(233),
 'RTePo8': np.int64(119),
 'RTePo9': np.int64(62),
 'RTePo10': np.int64(109),
 'REc1': np.int64(672),
 'REc2': np.int64(466),
 'REc3': np.int64(447),
 'REc4': np.int64(398),
 'REc5': np.int64(172),
 'REc6': np.int64(195),
 'REc7': np.int64(167),
 'REc8': np.int64(247),
 'RPHG1': np.int64(623),
 'RPHG2': np.int64(704),
 'RPHG3': np.int64(741),
 'RPHG4': np.int64(699),
 'RPHG5': np.int64(729),
 'RPHG6': np.int64(569),
 'RPHG7': np.int64(488),
 'RPHG8': np.int64(500),
 'RPHG9': np.int64(274),
 'RPHG10': np.int64(156),
 'RPHG11': np.int64(141),
 'RPHG12': np.int64(100),
 'RPHG13': np.int64(281),
 'RANT1': np.int64(83),
 'RANT2': np.int64(37),
 'RANT3': np.int64(94),
 'RANT4': np.int64(240),
 'RANT5': np.int64(249),
 'RANT6': np.int64(175),
 'RANT7': np.int64(260),
 'RANT8': np.int64(141),
 'RANT9': np.int64(60),
 'RANT10': np.int64(110),
 'RANT11': np.int64(236),
 'RANT12': np.int64(50),
 'RANT13': np.int64(28),
 'RANT14': np.int64(126),
 'RANT15': np.int64(325),
 'RANT16': np.int64(77),
 'RPuI1': np.int64(255),
 'RPuI2': np.int64(360),
 'RPuI3': np.int64(385),
 'RPuI4': np.int64(403),
 'RPuI5': np.int64(373),
 'RPuI6': np.int64(270),
 'RPuI7': np.int64(96),
 'RPuI8': np.int64(14),
 'RPuI9': np.int64(28),
 'RPuI10': np.int64(17),
 'RPuI11': np.int64(7),
 'RPuI12': np.int64(9),
 'RPuI13': np.int64(39),
 'RPuI14': np.int64(35),
 'RPuI15': np.int64(84),
 'RPuI16': np.int64(233),
 'ROFc1': np.int64(14),
 'ROFc2': np.int64(27),
 'ROFc3': np.int64(90),
 'ROFc4': np.int64(37),
 'ROFc5': np.int64(21),
 'ROFc6': np.int64(8),
 'ROFc7': np.int64(38),
 'ROFc8': np.int64(18),
 'ROFc9': np.int64(9),
 'ROFc10': np.int64(9),
 'ROFc11': np.int64(11),
 'ROFc12': np.int64(14),
 'ROFc13': np.int64(25),
 'ROFc14': np.int64(55),
 'RAIn1': np.int64(319),
 'RAIn2': np.int64(166),
 'RAIn3': np.int64(101),
 'RAIn4': np.int64(10),
 'RAIn5': np.int64(6),
 'RAIn6': np.int64(4),
 'RAIn7': np.int64(5),
 'RAIn8': np.int64(12),
 'RAIn9': np.int64(22),
 'RAIn10': np.int64(15),
 'RAIn11': np.int64(9),
 'RAIn12': np.int64(8)}

In [50]:
import pandas as pd
df = pd.read_csv(coordinates_csv)

In [51]:
import re
def _normalize_label(label: str) -> str:
    """Normalize electrode label to MNE channel name format (e.g. 'LAm-01' -> 'LAm1')."""
    m = re.match(r"([A-Za-z]+)-?0*([0-9]+)$", str(label))
    if m:
        return f"{m.group(1)}{int(m.group(2))}"
    return label

In [22]:
df

,label,atlas_label,GM,WM,CSF,x,y,z,mni_x,mni_y,mni_z
0,LAm-01,Hippocampus,0.992,0.992,0.002,-13.584,-20.118,37.439,-14.200,-9.554,-16.098
1,LAm-02,Amygdala,0.986,0.986,0.006,-16.990,-19.842,36.876,-17.839,-9.098,-16.606
2,LAm-03,Hippocampus,0.953,0.953,0.029,-20.441,-19.661,36.043,-21.572,-8.669,-17.590
3,LAm-04,Inferior Lateral Ventricle,0.975,0.975,0.013,-23.646,-19.522,35.343,-25.147,-8.468,-18.776
4,LAm-05,Inferior Lateral Ventricle,0.743,0.743,0.196,-27.093,-19.374,34.594,-28.865,-8.254,-20.670
...,...,...,...,...,...,...,...,...,...,...,...
303,RAIn-14,Caudal Middle Frontal,0.978,0.978,0.001,33.237,6.901,84.648,35.323,23.555,39.768
304,RAIn-15,Caudal Middle Frontal,0.991,0.991,0.002,33.637,7.502,88.022,36.841,23.857,42.726
305,RAIn-16,Caudal Middle Frontal,0.992,0.992,0.002,33.889,8.305,91.588,37.661,24.691,45.979
306,RAIn-17,Caudal Middle Frontal,0.992,0.992,0.002,34.109,8.994,94.810,37.421,26.009,49.111
307,RAIn-18,Caudal Middle Frontal,0.015,0.015,0.965,34.644,9.736,98.393,37.223,27.551,52.482

In [23]:
df["_normalized"] = df["label"].apply(_normalize_label)

In [27]:
import json

with open("/storage/cedar/cedar_cos/cos-lab-aivanova7/eayesh3/iEEG/EMOP0004/preprocessed/preprocessed_metadata.json",'r') as f:
    metadata = json.load(f)

seeg_set = set(metadata["ch_names_seeg"])

In [28]:
df = df[df["_normalized"].isin(seeg_set)].copy()
df

,label,atlas_label,GM,WM,CSF,x,y,z,mni_x,mni_y,mni_z,_normalized
0,LAm-01,Hippocampus,0.992,0.992,0.002,-13.584,-20.118,37.439,-14.200,-9.554,-16.098,LAm1
1,LAm-02,Amygdala,0.986,0.986,0.006,-16.990,-19.842,36.876,-17.839,-9.098,-16.606,LAm2
2,LAm-03,Hippocampus,0.953,0.953,0.029,-20.441,-19.661,36.043,-21.572,-8.669,-17.590,LAm3
3,LAm-04,Inferior Lateral Ventricle,0.975,0.975,0.013,-23.646,-19.522,35.343,-25.147,-8.468,-18.776,LAm4
4,LAm-05,Inferior Lateral Ventricle,0.743,0.743,0.196,-27.093,-19.374,34.594,-28.865,-8.254,-20.670,LAm5
...,...,...,...,...,...,...,...,...,...,...,...,...
297,RAIn-08,Pars Opercularis,0.991,0.991,0.001,31.792,2.965,63.811,37.274,16.456,13.313,RAIn8
298,RAIn-09,Pars Opercularis,0.985,0.985,0.001,32.051,3.623,67.638,36.342,16.308,18.390,RAIn9
299,RAIn-10,Pars Opercularis,0.986,0.986,0.001,32.305,4.387,71.150,35.028,17.997,22.721,RAIn10
300,RAIn-11,Rostral Middle Frontal,0.992,0.992,0.002,32.476,4.943,74.308,34.498,19.582,27.152,RAIn11
301,RAIn-12,Caudal Middle Frontal,0.991,0.991,0.002,32.867,5.558,77.413,34.951,20.511,31.882,RAIn12

In [29]:
bad_set = set(metadata["bad_channels"])

In [30]:
df["is_bad"] = df["_normalized"].apply(lambda ch: int(ch in bad_set))

In [33]:
df[210:230]

,label,atlas_label,GM,WM,CSF,x,y,z,mni_x,mni_y,mni_z,_normalized,is_bad
252,RANT-14,Superior Temporal,0.990,0.990,0.004,46.882,-17.208,45.733,53.114,-6.295,-1.322,RANT14,0
253,RANT-15,Superior Temporal,0.907,0.907,0.001,50.406,-17.637,44.458,57.367,-6.669,-2.752,RANT15,0
254,RANT-16,Superior Temporal,0.958,0.958,0.025,53.766,-17.687,43.414,62.217,-7.537,-4.536,RANT16,0
257,RPul-01,Pul,0.985,0.985,0.007,6.062,-42.450,54.509,8.436,-31.429,5.788,RPul1,0
258,RPul-02,Pul,0.989,0.989,0.004,9.537,-41.899,54.743,12.104,-31.392,6.145,RPul2,0
259,RPul-03,Pul,0.990,0.990,0.004,12.931,-41.403,55.108,15.826,-30.915,6.525,RPul3,0
260,RPul-04,Pul,0.992,0.992,0.002,16.436,-40.892,55.443,19.763,-30.358,6.935,RPul4,0
261,RPul-05,Pul,0.991,0.991,0.003,19.769,-40.427,55.647,23.891,-29.832,7.316,RPul5,0
262,RPul-06,Pul,0.980,0.980,0.001,23.189,-40.091,56.214,28.360,-28.992,8.053,RPul6,0
263,RPul-07,Insula,0.990,0.990,0.003,26.561,-39.572,56.261,32.671,-27.585,8.140,RPul7,0
264,RPul-08,Transverse Temporal,0.887,0.887,0.081,30.064,-38.933,56.813,36.708,-26.145,8.294,RPul8,0
265,RPul-09,Transverse Temporal,0.985,0.985,0.001,33.492,-38.411,56.859,40.585,-25.655,7.727,RPul9,0
266,RPul-10,Transverse Temporal,0.992,0.992,0.001,36.959,-37.980,57.264,44.649,-25.294,7.829,RPul10,0
267,RPul-11,Superior Temporal,0.989,0.989,0.004,40.412,-37.507,57.693,48.642,-25.020,8.454,RPul11,0
268,RPul-12,Superior Temporal,0.989,0.989,0.004,43.782,-36.946,57.788,52.171,-24.610,8.762,RPul12,0
269,RPul-13,Superior Temporal,0.980,0.980,0.010,47.365,-36.530,58.243,55.735,-24.446,9.364,RPul13,0
270,RPul-14,Superior Temporal,0.992,0.992,0.001,50.807,-36.184,58.508,59.206,-24.526,9.843,RPul14,0
271,RPul-15,Superior Temporal,0.966,0.966,0.001,54.262,-35.635,58.564,62.731,-24.415,10.102,RPul15,0
272,RPul-16,Superior Temporal,0.991,0.991,0.001,57.640,-34.908,58.928,66.012,-24.138,11.121,RPul16,0
275,ROFc-01,Medial Orbitofrontal,0.728,0.728,0.230,-0.710,12.469,32.788,4.228,20.540,-23.408,ROFc1,0

In [40]:
ied_ch_names = [str(ch) for ch in ied["ch_names"]]
channel_renames= [{"name": "RPuI", "new_name": "RPul"}]
    
for channel_name in channel_renames:
    matched = [(idx,ch) for idx,ch in enumerate(ied_ch_names) if ch.startswith(channel_name["name"])]
    for idx,ch in matched:
            new_ch_name = ch.replace(channel_name["name"], channel_name["new_name"])
            ied_ch_names[idx] = new_ch_name

In [41]:
    
wrong_channel_names = []
spike_counts = dict(zip(ied_ch_names, ied["channel_spike_counts"]))
spike_rates = dict(zip(ied_ch_names, ied["channel_spike_rates"]))
df["spike_count"] = df["_normalized"].map(spike_counts)
df["spike_rate"] = df["_normalized"].map(spike_rates)

In [42]:
df[210:230]

,label,atlas_label,GM,WM,CSF,x,y,z,mni_x,mni_y,mni_z,_normalized,is_bad,spike_count,spike_rate
252,RANT-14,Superior Temporal,0.990,0.990,0.004,46.882,-17.208,45.733,53.114,-6.295,-1.322,RANT14,0,126,1.388597
253,RANT-15,Superior Temporal,0.907,0.907,0.001,50.406,-17.637,44.458,57.367,-6.669,-2.752,RANT15,0,325,3.581698
254,RANT-16,Superior Temporal,0.958,0.958,0.025,53.766,-17.687,43.414,62.217,-7.537,-4.536,RANT16,0,77,0.848587
257,RPul-01,Pul,0.985,0.985,0.007,6.062,-42.450,54.509,8.436,-31.429,5.788,RPul1,0,255,2.810255
258,RPul-02,Pul,0.989,0.989,0.004,9.537,-41.899,54.743,12.104,-31.392,6.145,RPul2,0,360,3.967419
259,RPul-03,Pul,0.990,0.990,0.004,12.931,-41.403,55.108,15.826,-30.915,6.525,RPul3,0,385,4.242935
260,RPul-04,Pul,0.992,0.992,0.002,16.436,-40.892,55.443,19.763,-30.358,6.935,RPul4,0,403,4.441306
261,RPul-05,Pul,0.991,0.991,0.003,19.769,-40.427,55.647,23.891,-29.832,7.316,RPul5,0,373,4.110687
262,RPul-06,Pul,0.980,0.980,0.001,23.189,-40.091,56.214,28.360,-28.992,8.053,RPul6,0,270,2.975565
263,RPul-07,Insula,0.990,0.990,0.003,26.561,-39.572,56.261,32.671,-27.585,8.140,RPul7,0,96,1.057979
264,RPul-08,Transverse Temporal,0.887,0.887,0.081,30.064,-38.933,56.813,36.708,-26.145,8.294,RPul8,0,14,0.154289
265,RPul-09,Transverse Temporal,0.985,0.985,0.001,33.492,-38.411,56.859,40.585,-25.655,7.727,RPul9,0,28,0.308577
266,RPul-10,Transverse Temporal,0.992,0.992,0.001,36.959,-37.980,57.264,44.649,-25.294,7.829,RPul10,0,17,0.187350
267,RPul-11,Superior Temporal,0.989,0.989,0.004,40.412,-37.507,57.693,48.642,-25.020,8.454,RPul11,0,7,0.077144
268,RPul-12,Superior Temporal,0.989,0.989,0.004,43.782,-36.946,57.788,52.171,-24.610,8.762,RPul12,0,9,0.099185
269,RPul-13,Superior Temporal,0.980,0.980,0.010,47.365,-36.530,58.243,55.735,-24.446,9.364,RPul13,0,39,0.429804
270,RPul-14,Superior Temporal,0.992,0.992,0.001,50.807,-36.184,58.508,59.206,-24.526,9.843,RPul14,0,35,0.385721
271,RPul-15,Superior Temporal,0.966,0.966,0.001,54.262,-35.635,58.564,62.731,-24.415,10.102,RPul15,0,84,0.925731
272,RPul-16,Superior Temporal,0.991,0.991,0.001,57.640,-34.908,58.928,66.012,-24.138,11.121,RPul16,0,233,2.567802
275,ROFc-01,Medial Orbitofrontal,0.728,0.728,0.230,-0.710,12.469,32.788,4.228,20.540,-23.408,ROFc1,0,14,0.154289